### ISSUE TITLE
Citation not correct

### ISSUE THREAD

**Issue by L-Schwarz** [felixhoffmnn/nosql-book#1]
The citation of references does not confirm to APA standard. The reference is not within brackets, therefore it is confusing to read the text.

**Comment by felixhoffmnn** [comment]
This is not correct! To cite using APA-specific commands is required. Please refer to `content/code_beispiele.tex` for examples of valid APA citation commands. More examples can be found here https://ctan.net/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa-test.pdf.
